import 'package:multi_select_flutter/util/multi_select_item.dart';

class PtInteguDropDown {
  //Initialize values of dropdown
  List<MultiSelectItem<int>> integuDropDownItems = [
    MultiSelectItem(
      0,
      'Within Defined Limits',
    ),
    MultiSelectItem(
      1,
      'Clammy',
    ),
    MultiSelectItem(
      2,
      'Crepitus',
    ),
    MultiSelectItem(
      3,
      'Cyanotic',
    ),
    MultiSelectItem(
      4,
      'Diaphoretic',
    ),
    MultiSelectItem(
      5,
      'Dressing(s)',
    ),
    MultiSelectItem(
      6,
      'Dry',
    ),
    MultiSelectItem(
      7,
      'Ecchymosis',
    ),
    MultiSelectItem(
      8,
      'Erythema',
    ),
    MultiSelectItem(
      9,
      'Friable',
    ),
    MultiSelectItem(
      10,
      'Incision(s)',
    ),
    MultiSelectItem(
      11,
      'Inflammation',
    ),
    MultiSelectItem(
      12,
      'Jaundice',
    ),
    MultiSelectItem(
      13,
      'Lesion(s)',
    ),
    MultiSelectItem(
      14,
      'Other',
    ),
    MultiSelectItem(
      15,
      'Peeling',
    ),
    MultiSelectItem(
      16,
      'Petechiae',
    ),
    MultiSelectItem(
      17,
      'Purplish discoloration',
    ),
    MultiSelectItem(
      18,
      'Rash',
    ),
    MultiSelectItem(
      19,
      'Scab(s)',
    ),
    MultiSelectItem(
      20,
      'Scaling',
    ),
    MultiSelectItem(
      21,
      'Shiny',
    ),
    MultiSelectItem(
      22,
      'Skin Thickening',
    ),
    MultiSelectItem(
      23,
      'Staples',
    ),
    MultiSelectItem(
      24,
      'Stiches',
    ),
    MultiSelectItem(
      25,
      'Wound(s)',
    ),
    MultiSelectItem(
      26,
      'Wound Vacuum',
    ),
  ];
}
